# Generated by Django 2.0.5 on 2020-08-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardType', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('tran_date', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=60)),
                ('reward', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
            ],
        ),
    ]
